In [2]:
import pandas as pd
import numpy as np

1. Write a Pandas program to create a dataframe from a dictionary and display it.

In [3]:
dic = {'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96,72,83]}

pd.DataFrame(dic)

    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83

2. Write a Pandas program to create and display a DataFrame from a specified dictionary data which has the index labels.

In [4]:
exam_data = {
	'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
	'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
	'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
	'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']
}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

pd.DataFrame(exam_data, index=labels)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

3. Write a Pandas program to display a summary of the basic information about a specified DataFrame and its data.

In [5]:
pd.DataFrame(exam_data, index=labels).info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, a to j
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      10 non-null     object
 1   score     8 non-null      float64
 2   attempts  10 non-null     int64
 3   qualify   10 non-null     object
dtypes: float64(1), int64(1), object(2)
memory usage: 400.0+ bytes

4. Write a Pandas program to get the first 3 rows of a given DataFrame.

In [6]:
dados = pd.DataFrame(exam_data, index=labels)

In [7]:
# dados.iloc[:3]
dados.head(3)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes

5. Write a Pandas program to select the 'name' and 'score' columns from the following DataFrame.

In [8]:
pd.DataFrame(exam_data, index=labels)[['name', 'score']]

        name  score
a  Anastasia   12.5
b       Dima    9.0
c  Katherine   16.5
d      James    NaN
e      Emily    9.0
f    Michael   20.0
g    Matthew   14.5
h      Laura    NaN
i      Kevin    8.0
j      Jonas   19.0

6. Write a Pandas program to select the specified columns and rows from a given data frame. <br>
    -> Select 'name' and 'score' columns in rows 1, 3, 5, 6 from the following data frame.

In [9]:
# linhas = 1,3,5,6
# colunas 0,1
pd.DataFrame(exam_data, index=labels).iloc[[1,3,5,6],[0,1]]

      name  score
b     Dima    9.0
d    James    NaN
f  Michael   20.0
g  Matthew   14.5

7. Write a Pandas program to select the rows where the number of attempts in the examination is greater than 2.

In [10]:
dados = pd.DataFrame(exam_data, index=labels)
dados[dados['attempts'] > 2]

      name  score  attempts qualify
b     Dima    9.0         3      no
d    James    NaN         3      no
f  Michael   20.0         3     yes

8. Write a Pandas program to count the number of rows and columns of a DataFrame.

In [11]:
dados = pd.DataFrame(exam_data, index=labels)

print('Usando DataFrame.shape')
print(f'Number of Rows: {dados.shape[0]}')
print(f'Number of Columns: {dados.shape[1]}')

print('\nUsando DataFrame.axes')
print(f'Number of Rows: {len(dados.axes[0])}')
print(f'Number of Columns: {len(dados.axes[1])}')

Usando DataFrame.shape
Number of Rows: 10
Number of Columns: 4

Usando DataFrame.axes
Number of Rows: 10
Number of Columns: 4

9. Write a Pandas program to select the rows where the score is missing, i.e. is NaN.

In [12]:
dados = pd.DataFrame(exam_data, index=labels)

dados[dados['score'].isnull()]

    name  score  attempts qualify
d  James    NaN         3      no
h  Laura    NaN         1      no

10. Write a Pandas program to select the rows the score is between 15 and 20 (inclusive).

In [13]:
dados = pd.DataFrame(exam_data, index=labels)

print(dados[ (dados['score'] >=15 ) & ( dados['score'] <= 20) ])

print(dados[dados['score'].between(15,20)])

        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes
        name  score  attempts qualify
c  Katherine   16.5         2     yes
f    Michael   20.0         3     yes
j      Jonas   19.0         1     yes

11. Write a Pandas program to select the rows where number of attempts in the examination is less than 2 and score greater than 15.

In [14]:
dados = pd.DataFrame(exam_data, index=labels)

dados[ (dados['attempts'] < 2 ) & ( dados['score'] > 15) ]

    name  score  attempts qualify
j  Jonas   19.0         1     yes

12. Write a Pandas program to change the score in row 'd' to 11.5.

In [15]:
dados = pd.DataFrame(exam_data, index=labels)
dados.loc['d', 'score'] = 11.5
dados

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James   11.5         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

13. Write a Pandas program to calculate the sum of the examination attempts by the students.

In [16]:
dados = pd.DataFrame(exam_data, index=labels)
dados['attempts'].sum()

19

14. Write a Pandas program to calculate the mean of all students' scores. Data is stored in a dataframe.

In [17]:
dados = pd.DataFrame(exam_data, index=labels)
dados['score'].mean()

13.5625

15. Write a Pandas program to append a new row 'k' to data frame with given values for each column. Now delete the new row and return the original DataFrame.<br>
Values for each column will be:<br>
name : "Suresh", score: 15.5, attempts: 1, qualify: "yes", label: "k"

In [18]:
dados = pd.DataFrame(exam_data, index=labels)
dados.loc['k'] = ['Suresh', 15.5, 1, 'yes']
dados = dados.drop('k')

print(dados)

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

16. Write a Pandas program to sort the DataFrame first by 'name' in descending order, then by 'score' in ascending order.

In [19]:
dados = pd.DataFrame(exam_data, index=labels)

dados.sort_values(by=['name', 'score'], ascending=[False, True])

        name  score  attempts qualify
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
c  Katherine   16.5         2     yes
j      Jonas   19.0         1     yes
d      James    NaN         3      no
e      Emily    9.0         2      no
b       Dima    9.0         3      no
a  Anastasia   12.5         1     yes

17. Write a Pandas program to replace the 'qualify' column contains the values 'yes' and 'no' with True and False.

In [20]:
dados = pd.DataFrame(exam_data, index=labels)

#dados['qualify'].replace({'yes': True, 'no': False},inplace=True)

dados['qualify'] = dados['qualify'].map({'yes': True, 'no': False})

dados

        name  score  attempts  qualify
a  Anastasia   12.5         1     True
b       Dima    9.0         3    False
c  Katherine   16.5         2     True
d      James    NaN         3    False
e      Emily    9.0         2    False
f    Michael   20.0         3     True
g    Matthew   14.5         1     True
h      Laura    NaN         1    False
i      Kevin    8.0         2    False
j      Jonas   19.0         1     True

18. Write a Pandas program to change the name 'James' to 'Suresh' in name column of the DataFrame.

In [21]:
dados = pd.DataFrame(exam_data, index=labels)

#dados['name'].replace({'James': 'Suresh'},inplace=True)

dados['name'] = dados['name'].replace('James', 'Suresh')

dados

        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes
d     Suresh    NaN         3      no
e      Emily    9.0         2      no
f    Michael   20.0         3     yes
g    Matthew   14.5         1     yes
h      Laura    NaN         1      no
i      Kevin    8.0         2      no
j      Jonas   19.0         1     yes

19. Write a Pandas program to delete the 'attempts' column from the DataFrame.

In [22]:
dados = pd.DataFrame(exam_data, index=labels)
#dados.drop(columns=['attempts'], axis=1)
dados.pop('attempts')
dados

        name  score qualify
a  Anastasia   12.5     yes
b       Dima    9.0      no
c  Katherine   16.5     yes
d      James    NaN      no
e      Emily    9.0      no
f    Michael   20.0     yes
g    Matthew   14.5     yes
h      Laura    NaN      no
i      Kevin    8.0      no
j      Jonas   19.0     yes

20. Write a Pandas program to insert a new column in existing DataFrame.

In [23]:
dados = pd.DataFrame(exam_data, index=labels)
color = ['Red','Blue','Orange','Red','White','White','Blue','Green','Green','Red']
dados['color'] = color
dados

        name  score  attempts qualify   color
a  Anastasia   12.5         1     yes     Red
b       Dima    9.0         3      no    Blue
c  Katherine   16.5         2     yes  Orange
d      James    NaN         3      no     Red
e      Emily    9.0         2      no   White
f    Michael   20.0         3     yes   White
g    Matthew   14.5         1     yes    Blue
h      Laura    NaN         1      no   Green
i      Kevin    8.0         2      no   Green
j      Jonas   19.0         1     yes     Red

21. Write a Pandas program to iterate over rows in a DataFrame.

In [24]:
data = [{'name':'Anastasia', 'score':12.5}, {'name':'Dima','score':9}, {'name':'Katherine','score':16.5}]

dados = pd.DataFrame(data)

for index, row in dados.iterrows():
    print(row['name'], row['score'])

Anastasia 12.5
Dima 9.0
Katherine 16.5

22. Write a Pandas program to get list from DataFrame column headers.

In [25]:
dados = pd.DataFrame(exam_data, index=labels)

#list(dados.columns)
list(dados.columns.values)

['name', 'score', 'attempts', 'qualify']

23. Write a Pandas program to rename columns of a given DataFrame

In [26]:
d = {'col1': [1, 2, 3], 'col2': [4, 5, 6], 'col3': [7, 8, 9]}
dados = pd.DataFrame(data=d)

dados.rename(columns={'col1': 'Column1', 'col2': 'Column2', 'col3': 'Column3'}, inplace=True)

dados

   Column1  Column2  Column3
0        1        4        7
1        2        5        8
2        3        6        9

24 Write a Pandas program to select rows from a given DataFrame based on values in some columns.

In [32]:
dic = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

dados = pd.DataFrame(data=dic)

dados[dados['col1'] == 4]

   col1  col2  col3
1     4     5     8
3     4     7     0

25. Write a Pandas program to change the order of a DataFrame columns.

In [34]:
dic = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}

dados = pd.DataFrame(data=dic)

dados[['col3', 'col2', 'col1']]

   col3  col2  col1
0     7     4     1
1     8     5     4
2     9     6     3
3     0     7     4
4     1     8     5

26. Write a Pandas program to add one row in an existing DataFrame.

In [54]:
dic = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
dados = pd.DataFrame(dic)

dados.loc[len(dados)] = {'col1': 10, 'col2': 11, 'col3': 12}

dados

   col1  col2  col3
0     1     4     7
1     4     5     8
2     3     6     9
3     4     7     0
4     5     8     1
5    10    11    12

27. Write a Pandas program to write a DataFrame to CSV file using tab separator.

In [55]:
dic = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
dados = pd.DataFrame(data=d)

dados.to_csv('exercicio_27.csv')

28. Write a Pandas program to count city wise number of people from a given of data set (city, name of the person).

In [63]:
dados = pd.DataFrame({'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
'city': ['California', 'Los Angeles', 'California', 'California', 'California', 'Los Angeles', 'Los Angeles', 'Georgia', 'Georgia', 'Los Angeles']})

dados.groupby(["city"]).size().reset_index(name="Number of people")

          city  Number of people
0   California                 4
1      Georgia                 2
2  Los Angeles                 4

29. Write a Pandas program to delete DataFrame row(s) based on given column value.

In [64]:
d = {'col1': [1, 4, 3, 4, 5], 'col2': [4, 5, 6, 7, 8], 'col3': [7, 8, 9, 0, 1]}
df = pd.DataFrame(data=d)

df[df.col2 != 5]

   col1  col2  col3
0     1     4     7
2     3     6     9
3     4     7     0
4     5     8     1